services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: invoice-generator-api
    restart: unless-stopped
    env_file: ./backend/.env.production
    ports:
      - "8082:8080"
    networks:
      - default
      - expense-tracker-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    restart: unless-stopped
    depends_on:
      - backend

networks:
  expense-tracker-net:
    external: true
    name: expense-tracker_backend
