// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_accounts.sql

package sqlc

import (
	"context"
)

const bankAccountHasNonDraftInvoices = `-- name: BankAccountHasNonDraftInvoices :one
SELECT EXISTS (
    SELECT 1 FROM invoices
    WHERE bank_account_id = $1 AND status != 'draft' AND deleted_at IS NULL
) AS has_invoices
`

func (q *Queries) BankAccountHasNonDraftInvoices(ctx context.Context, bankAccountID int64) (bool, error) {
	row := q.db.QueryRow(ctx, bankAccountHasNonDraftInvoices, bankAccountID)
	var has_invoices bool
	err := row.Scan(&has_invoices)
	return has_invoices, err
}

const clearDefaultBankAccount = `-- name: ClearDefaultBankAccount :exec
UPDATE bank_accounts
SET is_default = false
WHERE company_id = $1 AND id != $2 AND deleted_at IS NULL
`

type ClearDefaultBankAccountParams struct {
	CompanyID int64 `json:"company_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) ClearDefaultBankAccount(ctx context.Context, arg ClearDefaultBankAccountParams) error {
	_, err := q.db.Exec(ctx, clearDefaultBankAccount, arg.CompanyID, arg.ID)
	return err
}

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts (company_id, bank_name, bank_address, account_holder, iban, swift, currency, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, bank_name, bank_address, account_holder, iban, swift, currency, is_default, created_at, updated_at, deleted_at
`

type CreateBankAccountParams struct {
	CompanyID     int64  `json:"company_id"`
	BankName      string `json:"bank_name"`
	BankAddress   string `json:"bank_address"`
	AccountHolder string `json:"account_holder"`
	Iban          string `json:"iban"`
	Swift         string `json:"swift"`
	Currency      string `json:"currency"`
	IsDefault     bool   `json:"is_default"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.CompanyID,
		arg.BankName,
		arg.BankAddress,
		arg.AccountHolder,
		arg.Iban,
		arg.Swift,
		arg.Currency,
		arg.IsDefault,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.BankAddress,
		&i.AccountHolder,
		&i.Iban,
		&i.Swift,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBankAccount = `-- name: DeleteBankAccount :exec
UPDATE bank_accounts
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteBankAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBankAccount, id)
	return err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT id, company_id, bank_name, bank_address, account_holder, iban, swift, currency, is_default, created_at, updated_at, deleted_at FROM bank_accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBankAccount(ctx context.Context, id int64) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccount, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.BankAddress,
		&i.AccountHolder,
		&i.Iban,
		&i.Swift,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBankAccountCompanyID = `-- name: GetBankAccountCompanyID :one
SELECT company_id FROM bank_accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBankAccountCompanyID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getBankAccountCompanyID, id)
	var company_id int64
	err := row.Scan(&company_id)
	return company_id, err
}

const listBankAccountsByCompany = `-- name: ListBankAccountsByCompany :many
SELECT id, company_id, bank_name, bank_address, account_holder, iban, swift, currency, is_default, created_at, updated_at, deleted_at FROM bank_accounts
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY is_default DESC, bank_name
`

func (q *Queries) ListBankAccountsByCompany(ctx context.Context, companyID int64) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccountsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankAccount{}
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BankName,
			&i.BankAddress,
			&i.AccountHolder,
			&i.Iban,
			&i.Swift,
			&i.Currency,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccount = `-- name: UpdateBankAccount :one
UPDATE bank_accounts
SET bank_name = $2,
    bank_address = $3,
    account_holder = $4,
    iban = $5,
    swift = $6,
    currency = $7,
    is_default = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, company_id, bank_name, bank_address, account_holder, iban, swift, currency, is_default, created_at, updated_at, deleted_at
`

type UpdateBankAccountParams struct {
	ID            int64  `json:"id"`
	BankName      string `json:"bank_name"`
	BankAddress   string `json:"bank_address"`
	AccountHolder string `json:"account_holder"`
	Iban          string `json:"iban"`
	Swift         string `json:"swift"`
	Currency      string `json:"currency"`
	IsDefault     bool   `json:"is_default"`
}

func (q *Queries) UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, updateBankAccount,
		arg.ID,
		arg.BankName,
		arg.BankAddress,
		arg.AccountHolder,
		arg.Iban,
		arg.Swift,
		arg.Currency,
		arg.IsDefault,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.BankAddress,
		&i.AccountHolder,
		&i.Iban,
		&i.Swift,
		&i.Currency,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
