// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clientHasNonDraftInvoices = `-- name: ClientHasNonDraftInvoices :one
SELECT EXISTS (
    SELECT 1 FROM invoices
    WHERE client_id = $1 AND status != 'draft' AND deleted_at IS NULL
) AS has_invoices
`

func (q *Queries) ClientHasNonDraftInvoices(ctx context.Context, clientID int64) (bool, error) {
	row := q.db.QueryRow(ctx, clientHasNonDraftInvoices, clientID)
	var has_invoices bool
	err := row.Scan(&has_invoices)
	return has_invoices, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (family_id, name, contact_person, email, address, vat_number, reg_number, contract_reference, contract_notes, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, family_id, name, contact_person, email, address, vat_number, reg_number, contract_reference, contract_notes, status, created_at, updated_at, deleted_at
`

type CreateClientParams struct {
	FamilyID          string      `json:"family_id"`
	Name              string      `json:"name"`
	ContactPerson     pgtype.Text `json:"contact_person"`
	Email             pgtype.Text `json:"email"`
	Address           string      `json:"address"`
	VatNumber         pgtype.Text `json:"vat_number"`
	RegNumber         pgtype.Text `json:"reg_number"`
	ContractReference pgtype.Text `json:"contract_reference"`
	ContractNotes     pgtype.Text `json:"contract_notes"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.FamilyID,
		arg.Name,
		arg.ContactPerson,
		arg.Email,
		arg.Address,
		arg.VatNumber,
		arg.RegNumber,
		arg.ContractReference,
		arg.ContractNotes,
		arg.Status,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.Address,
		&i.VatNumber,
		&i.RegNumber,
		&i.ContractReference,
		&i.ContractNotes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
UPDATE clients
SET deleted_at = NOW()
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type DeleteClientParams struct {
	ID       int64  `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient, arg.ID, arg.FamilyID)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, family_id, name, contact_person, email, address, vat_number, reg_number, contract_reference, contract_notes, status, created_at, updated_at, deleted_at FROM clients
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type GetClientParams struct {
	ID       int64  `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, arg.ID, arg.FamilyID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.Address,
		&i.VatNumber,
		&i.RegNumber,
		&i.ContractReference,
		&i.ContractNotes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, family_id, name, contact_person, email, address, vat_number, reg_number, contract_reference, contract_notes, status, created_at, updated_at, deleted_at FROM clients
WHERE family_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListClients(ctx context.Context, familyID string) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.ContactPerson,
			&i.Email,
			&i.Address,
			&i.VatNumber,
			&i.RegNumber,
			&i.ContractReference,
			&i.ContractNotes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsByStatus = `-- name: ListClientsByStatus :many
SELECT id, family_id, name, contact_person, email, address, vat_number, reg_number, contract_reference, contract_notes, status, created_at, updated_at, deleted_at FROM clients
WHERE family_id = $1 AND status = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListClientsByStatusParams struct {
	FamilyID string `json:"family_id"`
	Status   string `json:"status"`
}

func (q *Queries) ListClientsByStatus(ctx context.Context, arg ListClientsByStatusParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClientsByStatus, arg.FamilyID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.ContactPerson,
			&i.Email,
			&i.Address,
			&i.VatNumber,
			&i.RegNumber,
			&i.ContractReference,
			&i.ContractNotes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $3,
    contact_person = $4,
    email = $5,
    address = $6,
    vat_number = $7,
    reg_number = $8,
    contract_reference = $9,
    contract_notes = $10,
    status = $11
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
RETURNING id, family_id, name, contact_person, email, address, vat_number, reg_number, contract_reference, contract_notes, status, created_at, updated_at, deleted_at
`

type UpdateClientParams struct {
	ID                int64       `json:"id"`
	FamilyID          string      `json:"family_id"`
	Name              string      `json:"name"`
	ContactPerson     pgtype.Text `json:"contact_person"`
	Email             pgtype.Text `json:"email"`
	Address           string      `json:"address"`
	VatNumber         pgtype.Text `json:"vat_number"`
	RegNumber         pgtype.Text `json:"reg_number"`
	ContractReference pgtype.Text `json:"contract_reference"`
	ContractNotes     pgtype.Text `json:"contract_notes"`
	Status            string      `json:"status"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.ContactPerson,
		arg.Email,
		arg.Address,
		arg.VatNumber,
		arg.RegNumber,
		arg.ContractReference,
		arg.ContractNotes,
		arg.Status,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.ContactPerson,
		&i.Email,
		&i.Address,
		&i.VatNumber,
		&i.RegNumber,
		&i.ContractReference,
		&i.ContractNotes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
