// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const companyHasNonDraftInvoices = `-- name: CompanyHasNonDraftInvoices :one
SELECT EXISTS (
    SELECT 1 FROM invoices
    WHERE company_id = $1 AND status != 'draft' AND deleted_at IS NULL
) AS has_invoices
`

func (q *Queries) CompanyHasNonDraftInvoices(ctx context.Context, companyID int64) (bool, error) {
	row := q.db.QueryRow(ctx, companyHasNonDraftInvoices, companyID)
	var has_invoices bool
	err := row.Scan(&has_invoices)
	return has_invoices, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (family_id, name, contact_person, address, phone, vat_number, reg_number)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, family_id, name, contact_person, address, phone, vat_number, reg_number, created_at, updated_at, deleted_at
`

type CreateCompanyParams struct {
	FamilyID      string      `json:"family_id"`
	Name          string      `json:"name"`
	ContactPerson string      `json:"contact_person"`
	Address       string      `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	VatNumber     pgtype.Text `json:"vat_number"`
	RegNumber     pgtype.Text `json:"reg_number"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.FamilyID,
		arg.Name,
		arg.ContactPerson,
		arg.Address,
		arg.Phone,
		arg.VatNumber,
		arg.RegNumber,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.ContactPerson,
		&i.Address,
		&i.Phone,
		&i.VatNumber,
		&i.RegNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
UPDATE companies
SET deleted_at = NOW()
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type DeleteCompanyParams struct {
	ID       int64  `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error {
	_, err := q.db.Exec(ctx, deleteCompany, arg.ID, arg.FamilyID)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, family_id, name, contact_person, address, phone, vat_number, reg_number, created_at, updated_at, deleted_at FROM companies
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type GetCompanyParams struct {
	ID       int64  `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.ID, arg.FamilyID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.ContactPerson,
		&i.Address,
		&i.Phone,
		&i.VatNumber,
		&i.RegNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, family_id, name, contact_person, address, phone, vat_number, reg_number, created_at, updated_at, deleted_at FROM companies
WHERE family_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListCompanies(ctx context.Context, familyID string) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.ContactPerson,
			&i.Address,
			&i.Phone,
			&i.VatNumber,
			&i.RegNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $3,
    contact_person = $4,
    address = $5,
    phone = $6,
    vat_number = $7,
    reg_number = $8
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
RETURNING id, family_id, name, contact_person, address, phone, vat_number, reg_number, created_at, updated_at, deleted_at
`

type UpdateCompanyParams struct {
	ID            int64       `json:"id"`
	FamilyID      string      `json:"family_id"`
	Name          string      `json:"name"`
	ContactPerson string      `json:"contact_person"`
	Address       string      `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	VatNumber     pgtype.Text `json:"vat_number"`
	RegNumber     pgtype.Text `json:"reg_number"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.ContactPerson,
		arg.Address,
		arg.Phone,
		arg.VatNumber,
		arg.RegNumber,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.ContactPerson,
		&i.Address,
		&i.Phone,
		&i.VatNumber,
		&i.RegNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
