// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice_items.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (invoice_id, description, quantity, unit_price, total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, description, quantity, unit_price, total, created_at, updated_at
`

type CreateInvoiceItemParams struct {
	InvoiceID   int64           `json:"invoice_id"`
	Description string          `json:"description"`
	Quantity    decimal.Decimal `json:"quantity"`
	UnitPrice   decimal.Decimal `json:"unit_price"`
	Total       decimal.Decimal `json:"total"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.Total,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoiceItemsByInvoice = `-- name: DeleteInvoiceItemsByInvoice :exec
DELETE FROM invoice_items
WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceItemsByInvoice(ctx context.Context, invoiceID int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItemsByInvoice, invoiceID)
	return err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, description, quantity, unit_price, total, created_at, updated_at FROM invoice_items
WHERE invoice_id = $1
ORDER BY id
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID int64) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
