// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
WHERE family_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountInvoices(ctx context.Context, familyID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    user_id, family_id, company_id, client_id, bank_account_id,
    invoice_number, issue_date, due_date, currency, status, is_overdue,
    vat_rate, subtotal, vat_amount, total,
    contract_reference, external_reference, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'draft', false, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, user_id, family_id, company_id, client_id, bank_account_id, invoice_number, issue_date, due_date, currency, status, is_overdue, vat_rate, subtotal, vat_amount, total, contract_reference, external_reference, notes, created_at, updated_at, deleted_at
`

type CreateInvoiceParams struct {
	UserID            int32           `json:"user_id"`
	FamilyID          int32           `json:"family_id"`
	CompanyID         int64           `json:"company_id"`
	ClientID          int64           `json:"client_id"`
	BankAccountID     int64           `json:"bank_account_id"`
	InvoiceNumber     string          `json:"invoice_number"`
	IssueDate         pgtype.Date     `json:"issue_date"`
	DueDate           pgtype.Date     `json:"due_date"`
	Currency          string          `json:"currency"`
	VatRate           decimal.Decimal `json:"vat_rate"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	VatAmount         decimal.Decimal `json:"vat_amount"`
	Total             decimal.Decimal `json:"total"`
	ContractReference pgtype.Text     `json:"contract_reference"`
	ExternalReference pgtype.Text     `json:"external_reference"`
	Notes             pgtype.Text     `json:"notes"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.UserID,
		arg.FamilyID,
		arg.CompanyID,
		arg.ClientID,
		arg.BankAccountID,
		arg.InvoiceNumber,
		arg.IssueDate,
		arg.DueDate,
		arg.Currency,
		arg.VatRate,
		arg.Subtotal,
		arg.VatAmount,
		arg.Total,
		arg.ContractReference,
		arg.ExternalReference,
		arg.Notes,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.CompanyID,
		&i.ClientID,
		&i.BankAccountID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.Status,
		&i.IsOverdue,
		&i.VatRate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.ContractReference,
		&i.ExternalReference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
UPDATE invoices
SET deleted_at = NOW()
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type DeleteInvoiceParams struct {
	ID       int64 `json:"id"`
	FamilyID int32 `json:"family_id"`
}

func (q *Queries) DeleteInvoice(ctx context.Context, arg DeleteInvoiceParams) error {
	_, err := q.db.Exec(ctx, deleteInvoice, arg.ID, arg.FamilyID)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, user_id, family_id, company_id, client_id, bank_account_id, invoice_number, issue_date, due_date, currency, status, is_overdue, vat_rate, subtotal, vat_amount, total, contract_reference, external_reference, notes, created_at, updated_at, deleted_at FROM invoices
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type GetInvoiceParams struct {
	ID       int64 `json:"id"`
	FamilyID int32 `json:"family_id"`
}

func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.ID, arg.FamilyID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.CompanyID,
		&i.ClientID,
		&i.BankAccountID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.Status,
		&i.IsOverdue,
		&i.VatRate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.ContractReference,
		&i.ExternalReference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaxInvoiceSequence = `-- name: GetMaxInvoiceSequence :one
SELECT COALESCE(MAX(
    CAST(SUBSTRING(invoice_number FROM '[0-9]+$') AS INTEGER)
), 0) AS max_seq
FROM invoices
WHERE user_id = $1
  AND invoice_number LIKE $2
  AND deleted_at IS NULL
`

type GetMaxInvoiceSequenceParams struct {
	UserID        int32  `json:"user_id"`
	InvoiceNumber string `json:"invoice_number"`
}

func (q *Queries) GetMaxInvoiceSequence(ctx context.Context, arg GetMaxInvoiceSequenceParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxInvoiceSequence, arg.UserID, arg.InvoiceNumber)
	var max_seq interface{}
	err := row.Scan(&max_seq)
	return max_seq, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.user_id, i.family_id, i.company_id, i.client_id, i.bank_account_id, i.invoice_number, i.issue_date, i.due_date, i.currency, i.status, i.is_overdue, i.vat_rate, i.subtotal, i.vat_amount, i.total, i.contract_reference, i.external_reference, i.notes, i.created_at, i.updated_at, i.deleted_at,
       c.name AS company_name,
       cl.name AS client_name,
       (SELECT COUNT(*) FROM invoice_items WHERE invoice_id = i.id) AS items_count
FROM invoices i
JOIN companies c ON c.id = i.company_id
JOIN clients cl ON cl.id = i.client_id
WHERE i.family_id = $1 AND i.deleted_at IS NULL
ORDER BY i.issue_date DESC, i.created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesParams struct {
	FamilyID int32 `json:"family_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListInvoicesRow struct {
	ID                int64              `json:"id"`
	UserID            int32              `json:"user_id"`
	FamilyID          int32              `json:"family_id"`
	CompanyID         int64              `json:"company_id"`
	ClientID          int64              `json:"client_id"`
	BankAccountID     int64              `json:"bank_account_id"`
	InvoiceNumber     string             `json:"invoice_number"`
	IssueDate         pgtype.Date        `json:"issue_date"`
	DueDate           pgtype.Date        `json:"due_date"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	IsOverdue         bool               `json:"is_overdue"`
	VatRate           decimal.Decimal    `json:"vat_rate"`
	Subtotal          decimal.Decimal    `json:"subtotal"`
	VatAmount         decimal.Decimal    `json:"vat_amount"`
	Total             decimal.Decimal    `json:"total"`
	ContractReference pgtype.Text        `json:"contract_reference"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CompanyName       string             `json:"company_name"`
	ClientName        string             `json:"client_name"`
	ItemsCount        int64              `json:"items_count"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.FamilyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.CompanyID,
			&i.ClientID,
			&i.BankAccountID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.Currency,
			&i.Status,
			&i.IsOverdue,
			&i.VatRate,
			&i.Subtotal,
			&i.VatAmount,
			&i.Total,
			&i.ContractReference,
			&i.ExternalReference,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompanyName,
			&i.ClientName,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices
SET company_id = $3,
    client_id = $4,
    bank_account_id = $5,
    invoice_number = $6,
    issue_date = $7,
    due_date = $8,
    currency = $9,
    vat_rate = $10,
    subtotal = $11,
    vat_amount = $12,
    total = $13,
    contract_reference = $14,
    external_reference = $15,
    notes = $16
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, family_id, company_id, client_id, bank_account_id, invoice_number, issue_date, due_date, currency, status, is_overdue, vat_rate, subtotal, vat_amount, total, contract_reference, external_reference, notes, created_at, updated_at, deleted_at
`

type UpdateInvoiceParams struct {
	ID                int64           `json:"id"`
	FamilyID          int32           `json:"family_id"`
	CompanyID         int64           `json:"company_id"`
	ClientID          int64           `json:"client_id"`
	BankAccountID     int64           `json:"bank_account_id"`
	InvoiceNumber     string          `json:"invoice_number"`
	IssueDate         pgtype.Date     `json:"issue_date"`
	DueDate           pgtype.Date     `json:"due_date"`
	Currency          string          `json:"currency"`
	VatRate           decimal.Decimal `json:"vat_rate"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	VatAmount         decimal.Decimal `json:"vat_amount"`
	Total             decimal.Decimal `json:"total"`
	ContractReference pgtype.Text     `json:"contract_reference"`
	ExternalReference pgtype.Text     `json:"external_reference"`
	Notes             pgtype.Text     `json:"notes"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.ID,
		arg.FamilyID,
		arg.CompanyID,
		arg.ClientID,
		arg.BankAccountID,
		arg.InvoiceNumber,
		arg.IssueDate,
		arg.DueDate,
		arg.Currency,
		arg.VatRate,
		arg.Subtotal,
		arg.VatAmount,
		arg.Total,
		arg.ContractReference,
		arg.ExternalReference,
		arg.Notes,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.CompanyID,
		&i.ClientID,
		&i.BankAccountID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.Status,
		&i.IsOverdue,
		&i.VatRate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.ContractReference,
		&i.ExternalReference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoiceOverdue = `-- name: UpdateInvoiceOverdue :one
UPDATE invoices
SET is_overdue = $3
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, family_id, company_id, client_id, bank_account_id, invoice_number, issue_date, due_date, currency, status, is_overdue, vat_rate, subtotal, vat_amount, total, contract_reference, external_reference, notes, created_at, updated_at, deleted_at
`

type UpdateInvoiceOverdueParams struct {
	ID        int64 `json:"id"`
	FamilyID  int32 `json:"family_id"`
	IsOverdue bool  `json:"is_overdue"`
}

func (q *Queries) UpdateInvoiceOverdue(ctx context.Context, arg UpdateInvoiceOverdueParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceOverdue, arg.ID, arg.FamilyID, arg.IsOverdue)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.CompanyID,
		&i.ClientID,
		&i.BankAccountID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.Status,
		&i.IsOverdue,
		&i.VatRate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.ContractReference,
		&i.ExternalReference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $3
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, family_id, company_id, client_id, bank_account_id, invoice_number, issue_date, due_date, currency, status, is_overdue, vat_rate, subtotal, vat_amount, total, contract_reference, external_reference, notes, created_at, updated_at, deleted_at
`

type UpdateInvoiceStatusParams struct {
	ID       int64  `json:"id"`
	FamilyID int32  `json:"family_id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.FamilyID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.CompanyID,
		&i.ClientID,
		&i.BankAccountID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.Status,
		&i.IsOverdue,
		&i.VatRate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.ContractReference,
		&i.ExternalReference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
