// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type BankAccount struct {
	ID            int64              `json:"id"`
	CompanyID     int64              `json:"company_id"`
	BankName      string             `json:"bank_name"`
	BankAddress   string             `json:"bank_address"`
	AccountHolder string             `json:"account_holder"`
	Iban          string             `json:"iban"`
	Swift         string             `json:"swift"`
	Currency      string             `json:"currency"`
	IsDefault     bool               `json:"is_default"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Client struct {
	ID                int64              `json:"id"`
	FamilyID          string             `json:"family_id"`
	Name              string             `json:"name"`
	ContactPerson     pgtype.Text        `json:"contact_person"`
	Email             pgtype.Text        `json:"email"`
	Address           string             `json:"address"`
	VatNumber         pgtype.Text        `json:"vat_number"`
	RegNumber         pgtype.Text        `json:"reg_number"`
	ContractReference pgtype.Text        `json:"contract_reference"`
	ContractNotes     pgtype.Text        `json:"contract_notes"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Company struct {
	ID            int64              `json:"id"`
	FamilyID      string             `json:"family_id"`
	Name          string             `json:"name"`
	ContactPerson string             `json:"contact_person"`
	Address       string             `json:"address"`
	Phone         pgtype.Text        `json:"phone"`
	VatNumber     pgtype.Text        `json:"vat_number"`
	RegNumber     pgtype.Text        `json:"reg_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Invoice struct {
	ID                int64              `json:"id"`
	UserID            string             `json:"user_id"`
	FamilyID          string             `json:"family_id"`
	CompanyID         int64              `json:"company_id"`
	ClientID          int64              `json:"client_id"`
	BankAccountID     int64              `json:"bank_account_id"`
	InvoiceNumber     string             `json:"invoice_number"`
	IssueDate         pgtype.Date        `json:"issue_date"`
	DueDate           pgtype.Date        `json:"due_date"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	IsOverdue         bool               `json:"is_overdue"`
	VatRate           decimal.Decimal    `json:"vat_rate"`
	Subtotal          decimal.Decimal    `json:"subtotal"`
	VatAmount         decimal.Decimal    `json:"vat_amount"`
	Total             decimal.Decimal    `json:"total"`
	ContractReference pgtype.Text        `json:"contract_reference"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type InvoiceItem struct {
	ID          int64              `json:"id"`
	InvoiceID   int64              `json:"invoice_id"`
	Description string             `json:"description"`
	Quantity    decimal.Decimal    `json:"quantity"`
	UnitPrice   decimal.Decimal    `json:"unit_price"`
	Total       decimal.Decimal    `json:"total"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
