// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	BankAccountHasNonDraftInvoices(ctx context.Context, bankAccountID int64) (bool, error)
	ClearDefaultBankAccount(ctx context.Context, arg ClearDefaultBankAccountParams) error
	ClientHasNonDraftInvoices(ctx context.Context, clientID int64) (bool, error)
	CompanyHasNonDraftInvoices(ctx context.Context, companyID int64) (bool, error)
	CountInvoices(ctx context.Context, familyID string) (int64, error)
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error)
	DeleteBankAccount(ctx context.Context, id int64) error
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error
	DeleteInvoice(ctx context.Context, arg DeleteInvoiceParams) error
	DeleteInvoiceItemsByInvoice(ctx context.Context, invoiceID int64) error
	GetBankAccount(ctx context.Context, id int64) (BankAccount, error)
	GetBankAccountCompanyID(ctx context.Context, id int64) (int64, error)
	GetClient(ctx context.Context, arg GetClientParams) (Client, error)
	GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error)
	GetInvoice(ctx context.Context, arg GetInvoiceParams) (Invoice, error)
	GetMaxInvoiceSequence(ctx context.Context, arg GetMaxInvoiceSequenceParams) (interface{}, error)
	ListBankAccountsByCompany(ctx context.Context, companyID int64) ([]BankAccount, error)
	ListClients(ctx context.Context, familyID string) ([]Client, error)
	ListClientsByStatus(ctx context.Context, arg ListClientsByStatusParams) ([]Client, error)
	ListCompanies(ctx context.Context, familyID string) ([]Company, error)
	ListInvoiceItems(ctx context.Context, invoiceID int64) ([]InvoiceItem, error)
	ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error)
	UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error)
	UpdateInvoiceOverdue(ctx context.Context, arg UpdateInvoiceOverdueParams) (Invoice, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
}

var _ Querier = (*Queries)(nil)
